services:
  promocargobot:
    # Verifique se o link no seu GitHub Packages é exatamente este:
    image: ghcr.io/pholiveiraa/promocargobot:latest
    container_name: promocargobot
    depends_on:
      - lavalink
    env_file: .env
    restart: always
    networks:
      - bot-network

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    ports:
      - "2333:2333" # Mapeia a porta do container para a VPS
    environment:
      - SERVER_PORT=2333 # <--- ISSO AQUI FORÇA A PORTA 2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink/application.yml:/opt/lavalink/application.yml
      - ./lavalink/plugins:/opt/lavalink/plugins
    restart: always
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge