services:
  promocargobot:
    # Verifique se o link no seu GitHub Packages é exatamente este:
    image: ghcr.io/pholiveiraa/promocargobot:latest
    container_name: promocargobot
    depends_on:
      - lavalink
    env_file: .env
    restart: always
    networks:
      - bot-network

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    ports:
      - "8080:8080"
    environment:
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink/application.yml:/opt/lavalink/application.yml
    restart: always
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge