server: # Configurações do servidor
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 # Previne engasgos no áudio
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6 # Limite para não sobrecarregar o IP da VPS
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    scSearchExpirationLimit: 30
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
logging:
  file:
    path: ./logs/lavalink.log
  level:
    root: INFO
    lavalink: INFO